# This is a basic workflow to help you get started with Actions

name: Label PRs

on:
  pull_request_target:
    types: [opened]
  
jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: phillipj/node-pr-labeler@latest
